### ISSUE TITLE
Import fails on recipe XML file generated by Tournant

### ISSUE THREAD

**Issue by tomaszg7** [GourmandRecipeManager/gourmand#191]
I'm trying to run Gourmand on Gentoo (for a first time) with AppImage (the current built from HEAD). When I try to import my Android recipes from Tournant, it imports only part of the file bailing with:
```
emit error 1 Error during GXML2 Importer Traceback (most recent call last):
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/site-packages/gourmand/threadManager.py", line 107, in run
    self.do_run()
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/site-packages/gourmand/importers/xml_importer.py", line 76, in do_run
    self.parse = xml.sax.parse(self.fn, self.rh)
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/Python-3.10.16/Modules/pyexpat.c", line 475, in EndElement
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/xml/sax/expatreader.py", line 350, in end_element
    self._cont_handler.endElement(name)
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/site-packages/gourmand/plugins/import_export/gxml_plugin/gxml2_importer.py", line 45, in endElement
    self.commit_rec()
  File "/tmp/.mount_GourmaCmYzsO/opt/python3.10/lib/python3.10/site-packages/gourmand/importers/importer.py", line 243, in commit_rec
    r = self.rd.add_rec(self.rec, accept_ids=True)  # See doc on add_rec
TypeError: RecData.add_rec() got an unexpected keyword argument 'accept_ids'

emit done
```
Some recipes are imported successfully. The error leaves Gourmand in weird state with import progress button frozen and it is impossible to cancel the procedure to get rid of progress notification.

My guess is it is related to one recipe having a "sub-recipe" in Tournant. A minimal XML file exhibiting the error is attached. The first recipe gets imported correctly and only second one fails (the one without `<ingref>` tag). Surprisingly, it works correctly if the recipes in XML are in reverse order.

Generally it seems to be an overlap of two bugs: one with parsing `ingref` tags and the other with handling malformed XML content. 

[Rec.xml.gz](https://github.com/user-attachments/files/19374210/Rec.xml.gz)

**Comment by FriedrichFroebel** [comment]
Thanks for the report. Will see when I find the time to look into this, but of course everyone is invited to further dig into the cause as well.

**Comment by tomaszg7** [comment]
The cause seems to be https://github.com/GourmandRecipeManager/gourmand/commit/67b8c461f3ea76ed6b78dbeac74ed97d7e1d3560 which removed `accept_ids` from `def add_rec` in `db.py` but didn't remove associated code in `importer.py`. 

However I'm confused - I tried going down the history line seeing how it was wired previously. Seems to me `accept_ids` was introduced in https://github.com/GourmandRecipeManager/gourmand/commit/51ba5f392002f9f5c3278a31bc82632bf4eba3ff but as far as I can tell, it didn't do anything. Value of the flag seemed to me to be ignored.

Anyway, I updated `importer.py` by removing `accept_ids` parameter and everything seems to run correctly. I was able to import my Tournant database file. One recipe I had with sub-recipe in ingredient list looks to work fine. However the other recipe is referred only as `recipe` in the ingredient list. I'm not sure if it is expected behaviour. Anyway, I can submit this as a trivial PR.

![Image](https://github.com/user-attachments/assets/46956389-4512-4ce3-8e6d-7487b4eb07aa)

**Comment by FriedrichFroebel** [comment]
Thanks for the analysis. I would argue that fixing the failure is the correct approach here if we are unsure on what https://github.com/GourmandRecipeManager/gourmand/commit/bb0e71cf1c247c0f16290ee8b9cdb95a5079e358#diff-d850ba72078caf9dcaba8e64e7e3548e00792cedf63dae3a03dd0beb5210e05bR221 intended to actually do and/or never had a working implementation. In the best case, we are somehow able to test this as well.

If there is an issue with the references, this sounds like a separate issue which might need further analysis, although I am not sure what the intended display value would be here?

**Comment by tomaszg7** [comment]
Ok, created PR. Not sure it is a correct fix, but at least it doesn't make it worse ;D

As for references, I'm not sure, but I would think it would be more convenient to show the name of the recipe instead of just a word "recipe". I'll look into it.
